### PR TITLE
ION DID Provider and Resolver Implementation

### PR DESCRIPTION
**Pull request by rado0x54**
This branch provides support for `did:ion` in veramo.

Do not merge prior to the following issues being resolved:
- JWK Key handling in Veramo
- 50 char Key ID restriction in ION / `key.kid` in Veramo
- Transmute did-key dependencies for tooling (transitive in ion-tools)
- General dependency bloat: yarn.lock ++ 4000 lines.
- Source for verificationMethodTypes et al.
- `ion-tools` currently only supports `create` operation

Relates to #336

### CODE REVIEW

**Comment by rado0x54** [comment]
Relates to #336

**Comment by rado0x54** [comment]
The full ion-tools support is effectively blocked by https://github.com/decentralized-identity/ion-tools/issues/3 (Lack of update functionality)

**Comment by nklomp** [comment]
Just wanted to let you know we are working on creating a full implementation that supports recovery and updates, as well as generating keys on the fly and importing keys. It started out as a fork of this PR, as we need it for certain projects. But right now we need to have a fully working implementation soon. After the work in the URL is complete, we will create a PR to merge it into Veramo directly.

Next to the remaining work, there is a big issue currently with getting everything to work in React-Native. We had to fork several ION packages to get it to work. After the full implementation we will solve these ports in a nicer way as well.

If you are curious
https://github.com/Sphereon-Opensource/ssi-sdk/tree/feature/WAL-246/packages/ion-did-provider

**Comment by nklomp** [comment]
Probably it makes sense to close this PR, as it is superseded by https://github.com/uport-project/veramo/pull/987

**Comment by mirceanis** [comment]
Correct, thanks for flagging it!

**Pull request closed without merging**
