### PR TITLE
JSON-LD Signature Support

### LINKED ISSUE #273: Support of JSON-LD Signature Proofs
In addition to the currently supported JWT-based Verifiable Credentials, DAF should add native support for JSON-LD Signature Proofs.
An existing JS-based implementation can be found at [Digital Bazaar](https://github.com/digitalbazaar/vc-js).

In order to provide a generalized implementation of Verifiable Credential Use-Cases, the Veramo Core needs to provide three generic interfaces around Credential Handling:

1. Issue of Verifiable Credentials: As an Issuer I want to be able to create and sign Verifiable Credentials.

2. Verification of Verifiable Credentials (as a Holder)
As a Holder I need to proof the correct issuance of a Verifiable Credential. Furthermore, the Holder needs to be able to verify an updated Credential Status at any time. Lastly, on more complicated ZKP Proofing Schemes, the holder needs to verify the they are able to generate Verifiable Presentations.

3. Verification of Verifiable Presentation (as a Verifier)
As a Verifier I need to be able to proof the Validity of a Verifiable Presentation. This compounds:
- Correct Schema / Dataformats
- Correct Signature associated with a given Issuer
- Correct Signature associated with a given Holder (Holder binding)
- Unrevoked CredentialStatus
- Advanced: Trust Relationship to Issuer (Policy)
- Advanced: Trust Relationship to Holder (Policy)

2 and 3 might be combined into a unfied verification API.

For all use cases, the following credential formats and signature schemes need to be supported:
1. JWT Format with JWS Signature
2. JSON-LD Format with JSON-LD Proof Signature with the following signature suites:
a) EcdsaSecp256k1Signature2019
b) BbsBlsSignature2020 (separate Epic)

### PR DESCRIPTION
**Pull request by rado0x54**
## What's here:

This PR adds support for JSON LD Credentials via [vc-js](https://github.com/digitalbazaar/vc-js) and provides signature suite implementation for 
- `EcdsaSecp256k1RecoverySignature2020`
- `Ed25519Signature2018`

Other LD Context definitions and LD-Signature algorithms can be included dynamically within Veramo, but they need to be wrapped.
`LinkedDataSignature` Interfaces must be wrapped into `VeramoLdSignature` that allow for the translation of the Veramo (typed) ecosystem into `vc-js`. Futhermore, `VeramoLdSignature` offer quite the powerful callbacks into the documentLoader and signature process in order to solve incompatibilities between Veramo and `vc-js`. Please have a specific look at those functions.

Open Points (TBD link to related tickets).
- A challenge/response mechanism for VPs is currently not implemented in Veramos SDR flow and hardcoded challenge/responses are implemented for LD-based VPs

fixes #273

## new credential-ld package

Support for LD-Signatures is optional.
If the `@veramo/credential-ld` plugin is not used, then creation and verification of LD VC/VPs will fail with an error that hints at installing the package.

---
## Improved API to create VC/VP

This PR also introduces a few improvements to the ways credentials and presentations are created and verified.
For creation, the data types of the payloads required have been relaxed  See `CredentialPayload`/`PresentationPayload`.
Credential and Presentation related data types are now defined in `@veramo/core`, since they are shared by multiple 
packages (credential-w3c and credential-ld).

fixes #756

---
## Introduced API for verification!!

Finally, you can call `agent.verifyCredential()` and `agent.verifyPresentation()` and get a result instead of trying to force these through the `MessageHandler`.

The result is just a `boolean` for this PR, but it will be improved by #375

---
## new package for common converters
A new `@veramo/utils` package is now available that provides some common methods to help with low level conversions and the interpreting of some types.

--
## Follow up work
- [ ] add support for `EcdsaSecp256k1Signature2019`
- [ ] add support for `Ed25519Signature2020`
- [ ] add support for `EthereumEIP712Signature2021` #422 
- [ ] fix output of createCredential for JWT; people don't realize that Veramo returns the internal, parsed credential. Same for VP-JWT
- [ ] extend verification result from boolean to a more expressive output #375

### CODE REVIEW

**Comment by mirceanis** [comment]
relates to #375

**Comment by rado0x54** [comment]
- Add (optional) KeyID or VerificationMethodID to CreateCredential and pick key according to input.
- Add a "VeramoPresentationContext" that allows for issuanceDate and "remove" dynamic deletion within presentations.

**Comment by nklomp** [comment]
@mirceanis Sorry totally overlooked you asked a question.

What we are seeing and what is also my assumption is that most json-ld implementation are using ed25519 keys and then specifically Ed25519Signature2018 and these days Ed25519Signature2020 signature suites and verification methods, because of the blockchain heritage of a lot of DID methods. The latter version basically is a representation of the key in multibase format, so for ed25519 it is prefixing the proofValue of the verification method with the character 'z'.

Ed25519Signature2020: https://w3c-ccg.github.io/lds-ed25519-2020/
Ed25519Signature2018: https://w3c-ccg.github.io/lds-ed25519-2018/


The next interesting implementation is the ecdsa suites and verification methods, because of hardware support in mobile devices (as RSA), but they are less widely used in json-ld than ed25519 TTBOMK

**Review by simonas-notcat — APPROVED** [review]
Awesome work @rado0x54 @mirceanis !!

**Comment by siacomuzzi** [comment]
Great work, thank you!
Do you have plans to publish these changes to [npm](https://www.npmjs.com/package/@veramo/credential-w3c)?

**Pull request merged**
