### PR TITLE
fix(data-store-json): structuredClone

### PR DESCRIPTION
**Pull request by simonas-notcat**
Relates to https://github.com/uport-project/veramo/issues/857

### CODE REVIEW

**Comment by mirceanis** [comment]
Is it possible that #857 is being caused by having the storage object somehow contain `window` and thus causing the failure?

**Comment by simonas-notcat** [comment]
@mirceanis This is already what is happening under the hood:
https://github.com/ungap/structured-clone/blob/main/cjs/index.js#L20

I'm simply forcing this behavior.

**Comment by mirceanis** [comment]
> @mirceanis This is already what is happening under the hood

Haha, you are right, I did not think to look.

**Review by mirceanis — APPROVED** [review]
Looks good

**Pull request merged**
