### PR TITLE
feat(credential-ld): Added `Ed25519Signature2020` & `JsonWebSignature2020` experimental support

### PR DESCRIPTION
**Pull request by Eengineer1**
Linked issue & detailed approach #1003 .

### CODE REVIEW

**Comment by Eengineer1** [comment]
@mirceanis Thanks for mentioning.
I can recall from our early chat about dependecy issues.

What's included as well this PR:

- Bump `@types/eslint`, 8.4.3 -> 8.4.6.
- Bump `@types/eslint-scope`, 3.7.3 -> 3.7.4.
- Added as direct dependency in `test-react-app` to not clash with lower expected versions.
- Added node version compatible < `v16.x`, `multiformats@9.7.1` for multibase keys.

I'm pushing a fix on `@digitalcredentials/vc` <> `@transmute/json-web-signature` compatibility later today.

Questions:
- Are we open to exploring bumps, as long as the tests work as existing?
- To what extent are we open on refactoring tests to comply to bumps?

**Comment by mirceanis** [comment]
> Questions:
> 
> * Are we open to exploring bumps, as long as the tests work as existing?

What do you mean by _bumps_? version bumps?
Then yes. We try to keep up-to-date with all dependencies. We use renovate-bot to automatically bump dependencies that are safe.

> * To what extent are we open on refactoring tests to comply to bumps?

Tests should reflect real-world scenarios as close as possible. If we can't get our tests to run it's very likely that some user will face the same issues, so we are not going to include changes that we can't handle ourselves.
Refactoring tests is acceptable, as long as it doesn't hide any issues coming from dependencies.

We have a number of constraints that we impose on the packages in this repository:
  * they should all work in all 3 environments: nodejs, web, react-native
  * it's ok to also need workarounds for some environments as long as we know what the workarounds are
  * Veramo plugin method arguments and results should be serializable to JSON (this allows us to automatically compute the OpenAPI schemas)
  * plugins must not conflict with each-other; a user should be able to create a Veramo instance with all available plugins.

If we can't enforce these constraints on a new plugin then it should not be in this repository.

**Comment by Eengineer1** [comment]
@mirceanis Hey, this is ready for your review.

Kudos to the Transmute team on helping out untangle the non-polyfilled dependency knot upstream.

**Comment by mirceanis** [comment]
> @mirceanis Hey, this is ready for your review.

This looks good. Can you try to rebase to fix the conflicts?

**Comment by Eengineer1** [comment]
> > @mirceanis Hey, this is ready for your review.
> 
> This looks good. Can you try to rebase to fix the conflicts?

Resolved.

**Review by mirceanis — APPROVED** [review]
looks great, thank you for the contribution!

**Pull request merged**
